// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * logo field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * heading field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * subtitle field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Search Placeholder field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.search_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_placeholder: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LeftpanelDocumentDataSlicesSlice = WeatherOverviewSlice;

/**
 * Content for LeftPanel documents
 */
interface LeftpanelDocumentData {
  /**
   * Slice Zone field in *LeftPanel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: leftpanel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LeftpanelDocumentDataSlicesSlice>;
}

/**
 * LeftPanel document from Prismic
 *
 * - **API ID**: `leftpanel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LeftpanelDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LeftpanelDocumentData>,
    "leftpanel",
    Lang
  >;

type RightPanelDocumentDataSlicesSlice =
  | WeatherForecastSlice
  | WeatherFactsSlice;

/**
 * Content for right Panel documents
 */
interface RightPanelDocumentData {
  /**
   * Slice Zone field in *right Panel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: right_panel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RightPanelDocumentDataSlicesSlice>;
}

/**
 * right Panel document from Prismic
 *
 * - **API ID**: `right_panel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RightPanelDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RightPanelDocumentData>,
    "right_panel",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | LeftpanelDocument
  | RightPanelDocument;

/**
 * Item in *WeatherFacts → Default → Primary → Facts*
 */
export interface WeatherFactsSliceDefaultPrimaryFactsItem {
  /**
   * Icon field in *WeatherFacts → Default → Primary → Facts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_facts.default.primary.facts[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Fact Label field in *WeatherFacts → Default → Primary → Facts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_facts.default.primary.facts[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *WeatherFacts → Default → Primary*
 */
export interface WeatherFactsSliceDefaultPrimary {
  /**
   * Section Title field in *WeatherFacts → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_facts.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Facts field in *WeatherFacts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_facts.default.primary.facts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  facts: prismic.GroupField<Simplify<WeatherFactsSliceDefaultPrimaryFactsItem>>;
}

/**
 * Default variation for WeatherFacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for displaying multiple weather facts in a vertical list.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherFactsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WeatherFactsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WeatherFacts*
 */
type WeatherFactsSliceVariation = WeatherFactsSliceDefault;

/**
 * WeatherFacts Shared Slice
 *
 * - **API ID**: `weather_facts`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherFactsSlice = prismic.SharedSlice<
  "weather_facts",
  WeatherFactsSliceVariation
>;

/**
 * Item in *WeatherForecast → Five Day Forecast → Primary → Forecast Days*
 */
export interface WeatherForecastSliceFiveDayForecastPrimaryForecastDaysItem {
  /**
   * Day Label field in *WeatherForecast → Five Day Forecast → Primary → Forecast Days*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.five_day_forecast.primary.forecast_days[].day_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  day_label: prismic.KeyTextField;
}

/**
 * Primary content in *WeatherForecast → Five Day Forecast → Primary*
 */
export interface WeatherForecastSliceFiveDayForecastPrimary {
  /**
   * Section Title field in *WeatherForecast → Five Day Forecast → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.five_day_forecast.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Forecast Days field in *WeatherForecast → Five Day Forecast → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.five_day_forecast.primary.forecast_days[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  forecast_days: prismic.GroupField<
    Simplify<WeatherForecastSliceFiveDayForecastPrimaryForecastDaysItem>
  >;
}

/**
 * Five Day Forecast variation for WeatherForecast Slice
 *
 * - **API ID**: `five_day_forecast`
 * - **Description**: Displays a weather forecast for five days with day labels, weather icons, conditions, and temperature range.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherForecastSliceFiveDayForecast = prismic.SharedSliceVariation<
  "five_day_forecast",
  Simplify<WeatherForecastSliceFiveDayForecastPrimary>,
  never
>;

/**
 * Slice variation for *WeatherForecast*
 */
type WeatherForecastSliceVariation = WeatherForecastSliceFiveDayForecast;

/**
 * WeatherForecast Shared Slice
 *
 * - **API ID**: `weather_forecast`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherForecastSlice = prismic.SharedSlice<
  "weather_forecast",
  WeatherForecastSliceVariation
>;

/**
 * Primary content in *WeatherOverview → Main Weather Card → Primary*
 */
export interface WeatherOverviewSliceMainWeatherCardPrimary {
  /**
   * logo field in *WeatherOverview → Main Weather Card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.main_weather_card.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Search Placeholder field in *WeatherOverview → Main Weather Card → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.main_weather_card.primary.search_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_placeholder: prismic.KeyTextField;
}

/**
 * Main Weather Card variation for WeatherOverview Slice
 *
 * - **API ID**: `main_weather_card`
 * - **Description**: Primary weather card with city, date, time, current temperature, weather icon, min/max temperatures, and weather condition summary.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherOverviewSliceMainWeatherCard = prismic.SharedSliceVariation<
  "main_weather_card",
  Simplify<WeatherOverviewSliceMainWeatherCardPrimary>,
  never
>;

/**
 * Slice variation for *WeatherOverview*
 */
type WeatherOverviewSliceVariation = WeatherOverviewSliceMainWeatherCard;

/**
 * WeatherOverview Shared Slice
 *
 * - **API ID**: `weather_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherOverviewSlice = prismic.SharedSlice<
  "weather_overview",
  WeatherOverviewSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      LeftpanelDocument,
      LeftpanelDocumentData,
      LeftpanelDocumentDataSlicesSlice,
      RightPanelDocument,
      RightPanelDocumentData,
      RightPanelDocumentDataSlicesSlice,
      AllDocumentTypes,
      WeatherFactsSlice,
      WeatherFactsSliceDefaultPrimaryFactsItem,
      WeatherFactsSliceDefaultPrimary,
      WeatherFactsSliceVariation,
      WeatherFactsSliceDefault,
      WeatherForecastSlice,
      WeatherForecastSliceFiveDayForecastPrimaryForecastDaysItem,
      WeatherForecastSliceFiveDayForecastPrimary,
      WeatherForecastSliceVariation,
      WeatherForecastSliceFiveDayForecast,
      WeatherOverviewSlice,
      WeatherOverviewSliceMainWeatherCardPrimary,
      WeatherOverviewSliceVariation,
      WeatherOverviewSliceMainWeatherCard,
    };
  }
}
